# Generated by Django 4.1 on 2024-01-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="initial_consonant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="상품 이름"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="상품 이름"),
        ),
    ]
